# NumPy
NumPy (or Numpy) is a Linear Algebra Library for Python

In [1]:
import numpy as np

# Numpy has many built-in functions and capabilities.will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. 
Let's start by discussing.

Numpy Arrays


In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix=[1,2,3,4]

In [7]:
np.array(my_matrix)

array([1, 2, 3, 4])

In [8]:
my_matrix=[1,2,3,4],[4,5,6],[3,6]

In [9]:
np.array(my_matrix)

array([list([1, 2, 3, 4]), list([4, 5, 6]), list([3, 6])], dtype=object)

In [12]:
my_matrix=[[1,2,3],[4,5,6],[3,6,1]]

In [13]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [3, 6, 1]])

In [14]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [15]:
list(1,10)

TypeError: list expected at most 1 argument, got 2

In [17]:
list('10')

['1', '0']

In [20]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [21]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.ones(3)

array([1., 1., 1.])

In [32]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [34]:
np.random.rand(1,10)

array([[0.10426695, 0.10425907, 0.37584874, 0.2145268 , 0.83415448,
        0.97233904, 0.82902442, 0.25479003, 0.73878545, 0.15121055]])

In [35]:
np.random.rand(2,10)

array([[0.38736458, 0.42853295, 0.76610954, 0.55300229, 0.94216055,
        0.09807261, 0.61256691, 0.16118901, 0.44093519, 0.48482987],
       [0.69023563, 0.41470623, 0.03640991, 0.90615582, 0.79785367,
        0.43587183, 0.72081832, 0.33285067, 0.5669511 , 0.71595587]])

In [37]:
np.random.rand(5,5)

array([[0.5888083 , 0.41669314, 0.00291659, 0.85867207, 0.83718623],
       [0.83281727, 0.26063909, 0.41554096, 0.24254482, 0.49237054],
       [0.9486086 , 0.40142227, 0.30829043, 0.30661439, 0.57267519],
       [0.97486226, 0.81372045, 0.32505367, 0.04395366, 0.427688  ],
       [0.18770524, 0.76108823, 0.0253654 , 0.14533992, 0.51143696]])

In [40]:
np.random.randint(1,10)

6

In [41]:
np.random.randint(1,20,2)

array([11,  5])

In [44]:
arr=np.arange(5)

In [45]:
arr

array([0, 1, 2, 3, 4])

In [47]:
ranarr=np.arange(1,100,10)

In [48]:
ranarr

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [53]:
ranarr=np.random.randint(1,100,10)

In [54]:
ranarr

array([ 3, 32, 14, 54, 44, 83, 84, 31,  1, 44])

In [55]:
ranarr.max()

84

In [56]:
ranarr.min()

1

In [57]:
ranarr.avg()

AttributeError: 'numpy.ndarray' object has no attribute 'avg'

In [58]:
arr.shape

(5,)

In [62]:
arr.reshape(1,1)

ValueError: cannot reshape array of size 5 into shape (1,1)